import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { getJWTSession, logout } from "@/lib/actions";
import TanstackProvider from "@/providers/TanstackProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import AvatarPage from "./components/Avatar";

export const metadata: Metadata = {
  title: "Create Next App",

  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getJWTSession();

  return (
    <html
      lang="en"
      className="p-6
    "
    >
      <body className={` antialiased`}>
        <nav className="flex justify-between items-center mb-4">
          <ul className="flex gap-6">
            <li>
              <Link href={"/"}>Home</Link>
            </li>
            <li>
              <Link href={"/about"}>About</Link>
            </li>
            <li>
              <Link href={"/blogs"}>Blogs</Link>
            </li>
            <li>
              <Link href={"/posts"}>Posts</Link>
            </li>
            <li>
              <Link href={"/dashboard"}>Dashboard</Link>
            </li>
            <li>
              {session ? (
                <form action={logout}>
                  <button
                    type="submit"
                    className="text-red-600 hover:underline"
                  >
                    Logout
                  </button>
                </form>
              ) : (
                <Link href="/login">Login</Link>
              )}
            </li>
            <li>
              <Link href={"/charts"}>Charts</Link>
            </li>
            <li>
              <Link href={"/shop"}>Shop</Link>
            </li>
          </ul>
          {session?.email && (
            <div
              className="text-sm text-gray-600 flex items-center
            gap-2"
            >
              Logged in as <AvatarPage size={36} />
              <span className="font-medium text-orange-300">
                {session.email}
              </span>
            </div>
          )}
        </nav>
        <hr />
        <AntdRegistry>
          <TanstackProvider>{children}</TanstackProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
